### ISSUE TITLE
Getting "There were no results found" error message

### ISSUE THREAD

**Issue by benklocek** [mt-support/tribe-ext-instructor-linked-post-type#5]
I've used this to add an "Instructors" post type, but when activated, it throws a warning "There were no results found" when there are no events on the first day of the month, even if there are events in the rest of the month. 

Commenting out https://github.com/mt-support/tribe-ext-instructor-linked-post-type/blob/master/tribe-ext-instructor-linked-post-type.php#L1162 does the trick, but it should be looked at.

**Comment by cliffordp** [comment]
@benklocek Thanks for the detailed response. GitHub issues isn't part of our Extensions workflow so please log a ticket with this information at support.theeventscalendar.com

Thank you!
